[project]
name = "researchassistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "aiosqlite>=0.22.1",
    "arxiv>=2.4.0",
    "faiss-cpu>=1.13.2",
    "fastapi>=0.128.8",
    "langchain>=1.2.9",
    "langchain-anthropic>=1.3.2",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.2.0",
    "langchain-openai>=1.1.8",
    "langchain-pinecone>=0.2.13",
    "langgraph>=1.0.8",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "mlflow>=3.9.0",
    "pinecone-client>=6.0.0",
    "prometheus-client>=0.24.1",
    "pydantic>=2.12.5",
    "pypdf>=6.7.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "requests>=2.32.5",
    "streamlit>=1.54.0",
    "tavily-python>=0.7.21",
    "uvicorn>=0.40.0",
]
